name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/checkout@v4
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install NPM Dependencies
      run: npm install
    - name: Build Site
      run: npm run prod
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './build_production'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    # runs-on: ubuntu-latest
    # steps:
    # - name: Stage Files
    #   run: git add -f build_production
    # - name: Commit
    #   run: |
    #     git config --local user.email "actions@github.com"
    #     git config --local user.name "GitHub Actions"
    #     git commit -m "Build for deploy"
    # - name: Publish
    #   run: |
    #     git subtree split --prefix build_production -b gh-pages
    #     git push -f origin gh-pages:gh-pages